name: Telegram Notify

on: [push]
  
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Custom Message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELESEAN }}
        token: ${{ secrets.TELETOKEN }}
        args: There has been a ${{ github.event_name }} event in ${{ github.ref }} recently from ${{ github.actor }}. \n RUN_ID; ${{ github.run_id}} \n SHA; ${{ github.sha}} \n SERVER_URL; ${{ github.server_url}} \n API_URL; ${{ github.api_url }}
